# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coins',
            field=models.BigIntegerField(default=0),
        ),
    ]
