# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0002_auto_20160516_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='building_json',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
