# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-25 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup', '0003_player_building_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coins',
            field=models.FloatField(default=0),
        ),
    ]
