# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-09 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagion.League')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagion.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagion.Season'),
            preserve_default=False,
        ),
    ]
