# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-16 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='postponed_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postposted_from', to='leagion.Match'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(0, 'NotStarted'), (1, 'Completed'), (2, 'Postponed')], default=0),
        ),
    ]
