# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0002_auto_20171214_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
