# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-15 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0002_auto_20170409_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='roster',
            name='players',
        ),
        migrations.AddField(
            model_name='batter',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leagion.Roster'),
        ),
        migrations.AddField(
            model_name='roster',
            name='batters',
            field=models.ManyToManyField(related_name='_roster_batters_+', through='leagion.Batter', to=settings.AUTH_USER_MODEL),
        ),
    ]
