# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-15 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0002_match_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='leagion.Match'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='players',
            field=models.ManyToManyField(related_name='_roster_players_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leagion.Team'),
        ),
    ]
