# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-15 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0003_auto_20170415_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='away_roster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='away_rosters', to='leagion.Roster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='home_roster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='home_rosters', to='leagion.Roster'),
            preserve_default=False,
        ),
    ]
