# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-15 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0004_auto_20170415_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='batters',
        ),
        migrations.AddField(
            model_name='roster',
            name='players',
            field=models.ManyToManyField(through='leagion.Batter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batter',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batters', to='leagion.Roster'),
        ),
    ]
