# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-22 00:11
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields

def forwards(apps, schema_editor):
    User = apps.get_model('leagion', 'User')
    import faker, re
    F = faker.Faker("en_ca") #seed canadian numbers, we'll figure out international later
    users = User.objects.all()

    print("Total users to update phonenumbers: %i" %len(users))
    for i, user in enumerate(users):
        if i % 25 == 0:
            print ("updating %s" % i)

        #strip extensions
        num = F.phone_number()
        search = re.search("\W*x.*", num);
        if search:
            num = num.replace(search.group(), "")

        user.default_phonenumber = num

        alt = F.phone_number()
        search = re.search("\W*x.*", alt);
        if search:
            alt = num.replace(search.group(), "")
        user.alt_phonenumber = alt

        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0005_auto_20170415_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alt_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='default_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.RunPython(forwards),
    ]
