# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-17 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0006_auto_20170521_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captains',
            field=models.ManyToManyField(related_name='captain_of_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
