# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-19 04:32
from __future__ import unicode_literals

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('leagion', '0007_team_captains'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
