# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-09 02:56
from __future__ import unicode_literals

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('leagion', '0009_auto_20170908_2252'), ('leagion', '0010_auto_20170908_2254')]

    dependencies = [
        ('leagion', '0008_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=address.models.AddressField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
