# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-17 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0009_auto_20170908_2252_squashed_0010_auto_20170908_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_rosters', to='leagion.Roster'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_rosters', to='leagion.Roster'),
        ),
    ]
