# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0010_auto_20170916_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='leagues_commissioned',
            field=models.ManyToManyField(related_name='league_commissioners', to='leagion.League'),
        ),
        migrations.AddField(
            model_name='user',
            name='teams_captained',
            field=models.ManyToManyField(related_name='team_captains', to='leagion.Team'),
        ),
    ]
