# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-26 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0011_auto_20170925_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_commissioner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teams_captained',
        ),
    ]
