# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-02 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0012_auto_20170926_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='196E3D', max_length=6),
        ),
    ]
