# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-26 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import leagion.models.team
import leagion.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0014_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=leagion.models.user.get_avatar_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to=leagion.models.team.get_logo_path),
        ),
    ]
