# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-28 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0015_auto_20171026_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
