# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-20 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0016_auto_20171028_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='leagues_commissioned',
        ),
        migrations.AddField(
            model_name='league',
            name='commissioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leagues_commissioned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
