# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-14 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagion', '0018_auto_20171208_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='leagion.League'),
            preserve_default=False,
        ),
    ]
